search-form functionality
codingknite/hired pull request #1
Opened 2021-02-26 14:40 UTC by codingknite

Let me know if you'd like me to explain what I'm trying to do in the PR or if it's not necessary

2021-02-27 09:55 UTC, idiglove requested changes

2021-02-27 09:58 UTC, codingknite commented on src/components/HomePage.jsx
> +      `https://github-api-next.vercel.app/api/positions${
Okay....Is that a hook?

2021-02-27 10:00 UTC, idiglove commented on src/components/HomePage.jsx
> +      `https://github-api-next.vercel.app/api/positions${
I dont think it's applicable here, but u can try.. not entirely sure tbh

2021-02-27 10:00 UTC, codingknite commented on src/components/JobListings.jsx
> +        <section className="job-listing" key={job.id}>
Oh yeah I was using Sass for this one...that's why I have classNames all over.

2021-02-27 10:01 UTC, codingknite commented on src/components/HomePage.jsx
> +              {selectedTerms.location}{" "}
That was prettier I think

2021-02-27 10:01 UTC, codingknite commented on src/components/HomePage.jsx
> +        <form className="search-bar" onSubmit={handleSubmit}>
Challenge Accepted

2021-02-27 10:02 UTC, codingknite commented
Okay Let me fix these. Thanks

2021-02-27 10:02 UTC, idiglove commented on src/components/HomePage.jsx
> +              {selectedTerms.location}{" "}
ohh, you needed the space?

2021-02-27 10:03 UTC, idiglove commented on src/components/JobListings.jsx
> +        <section className="job-listing" key={job.id}>
I see. Would you like to use a css framework for this?

2021-02-27 10:05 UTC, codingknite commented on src/components/HomePage.jsx
> +              {selectedTerms.location}{" "}
No not really, I just wrote it normally like I would but then when I save prettier sort of formats the code and adds those spaces

2021-02-27 10:07 UTC, idiglove commented on src/components/HomePage.jsx
> +              {selectedTerms.location}{" "}
Oh I didnt know it can do that. Looks really awkward and unnecessary though. is it ok to find a way to turn off that feature?

2021-02-27 10:09 UTC, codingknite commented on src/components/HomePage.jsx
> +      `https://github-api-next.vercel.app/api/positions${
Perhaps you mean I should write a custom hook? The form has 3 fields but all of them are not compulsory.
Am trying to pass parameters in the API based on whether or not the fields are filled in.

2021-02-27 10:11 UTC, codingknite commented on src/components/HomePage.jsx
> +              {selectedTerms.location}{" "}
I agree...very unnecessary. I'll turn it off.

2021-02-27 10:12 UTC, codingknite commented on src/components/JobListings.jsx
> +        <section className="job-listing" key={job.id}>
I'd never used Sass for a project so I thought maybe I should give it a shot. I could still use styled-components. You think so?

2021-02-27 10:13 UTC, idiglove commented on src/components/HomePage.jsx
> +      `https://github-api-next.vercel.app/api/positions${
Yea I was thinking a custom helper, just a common function like in a util/helper.js would do.
Because I dont know if a React hook will be accepted as a fetch param

2021-02-27 10:14 UTC, idiglove commented on src/components/JobListings.jsx
> +        <section className="job-listing" key={job.id}>
Styled components would be a good experience too. You can use Sass with it too

2021-02-27 10:16 UTC, codingknite commented on src/components/HomePage.jsx
> +      `https://github-api-next.vercel.app/api/positions${
Ok I think I get it...let me try and see if I can make it a bit cleaner.

2021-02-27 10:18 UTC, codingknite commented on src/components/JobListings.jsx
> +        <section className="job-listing" key={job.id}>
Okay cool 👍

2021-02-27 23:47 UTC, codingknite commented
Hey @idiglove So I just made some changes based on what we discussed.
I implemented formik and the custom hook plus worked on the confusing query! 
Looks a little bit cleaner 😄

2021-02-28 01:09 UTC, idiglove requested changes

2021-02-28 01:09 UTC, idiglove commented on src/components/Header.jsx
> +          <h2>JOB BOARD FOR DEVELOPERS AND CREATIVE PROS</h2>
Just do a text-transform: uppercase
What you did will be read by screen readers letter by letter

2021-02-28 01:09 UTC, idiglove commented on src/components/HomePage.scss
> +  padding: 1rem;
Good job for using rem! :)

2021-02-28 01:09 UTC, idiglove commented on src/components/JobListings.jsx
> +  const generateDate = (date) => {
use a date plugin like DayJS or date-fns instead
Then put in a util/helper again :)

2021-02-28 01:09 UTC, idiglove commented on src/services/useFetch.js
> +        isMounted.current = true;
Do you really need this ref ?

2021-02-28 10:53 UTC, codingknite commented on src/components/HomePage.jsx
> +              disabled={pageNumber > 1 ? false : true}
That's brilliant 😄

2021-02-28 10:55 UTC, codingknite commented on src/services/useFetch.js
> +        isMounted.current = true;
I used it to make sure that the API call runs when the component is mounted....should the user navigate away before the API call is made. That's what I thought

2021-02-28 19:50 UTC, codingknite commented on src/components/HomePage.jsx
> +                setPageNumber((pageNumber) => pageNumber - 1);
For this I thought that if you're updating state and you need a reference to the current state you would need to use the function form of setState(). Is thist only applicable to complex state like Arrays and Objects?

2021-02-28 19:55 UTC, codingknite commented on src/components/Header.jsx
> +          <h2>JOB BOARD FOR DEVELOPERS AND CREATIVE PROS</h2>
Thanks for pointing this out. I applied the style in a sass file but am going to use styled-components for the entire app.
I usually do the styling last after the entire app functions

2021-02-28 21:41 UTC, codingknite commented
Hey Faith! So I pretty much made all the changes you suggested except the useRef part as I need your feedback on it.

I also need help with some part of the code.
In the HomePage components on line 21,22 & 25, there I declare state for a search URL. That searchUrl is generated once the user fills in the form. But by default, once the application starts for the first time the url should be null for obvious reasons. But setting it to null yields an error.

So I decided to use a fake url: `initUrl (line 21)` which for a fact doesn't return any data once called. Therefore it returns an empty array.

On line 161 I have a condition that only displays SearchedJobs if the array isn't empty i.e an API call was made and we got some data back.
This work perfectly except that there are some queries to the API which could potentially return no data i.e an empty array.

My Question: How can I have the url called only when its not null (desired initial state)?
Btw I call the API on line 58.

Sorry very long question 🤦

2021-02-28 23:44 UTC, idiglove commented on src/services/useFetch.js
> +        isMounted.current = true;
Ok lets wait for react-query

2021-02-28 23:44 UTC, idiglove commented on src/components/HomePage.jsx
> +                setPageNumber((pageNumber) => pageNumber - 1);
pageNumber is already a reference of the state

2021-02-28 23:45 UTC, idiglove commented on src/components/HomePage.jsx
> +    if (location && jobtype) {
i havent seen you do this

2021-02-28 23:48 UTC, idiglove commented
> Hey Faith! So I pretty much made all the changes you suggested except the useRef part as I need your feedback on it.
> 
> I also need help with some part of the code.
> In the HomePage components on line 21,22 & 25, there I declare state for a search URL. That searchUrl is generated once the user fills in the form. But by default, once the application starts for the first time the url should be null for obvious reasons. But setting it to null yields an error.
> 
> So I decided to use a fake url: `initUrl (line 21)` which for a fact doesn't return any data once called. Therefore it returns an empty array.
> 
> On line 161 I have a condition that only displays SearchedJobs if the array isn't empty i.e an API call was made and we got some data back.
> This work perfectly except that there are some queries to the API which could potentially return no data i.e an empty array.
> 
> My Question: How can I have the url called only when its not null (desired initial state)?
> Btw I call the API on line 58.
> 
> Sorry very long question 🤦

Cant you just set searchUrl to be an empty string or null.
Are you having problems using useFetch with an empty string or null?

Inside useFetch, make a condition that if it the searchURL is null, dont make an api call.

2021-03-01 04:26 UTC, codingknite commented on src/components/HomePage.jsx
> +    if (location && jobtype) {
I made a new file under the services folder called urlConstructor.js. Referenced it on line 42. 
I thought this is what you meant. Maybe I didn't get you properly.

2021-03-01 04:29 UTC, idiglove commented on src/components/HomePage.jsx
> +    if (location && jobtype) {
alright sorry i missed that somehow. good job :)

2021-03-01 04:42 UTC, codingknite commented on src/components/HomePage.jsx
> +    if (location && jobtype) {
Its okay. I think we can merge this now?

2021-03-01 05:02 UTC, idiglove commented on src/components/HomePage.jsx
> +    if (location && jobtype) {
Have you resolved your problem with passing null or empty string to useFetch?

2021-03-01 07:19 UTC, codingknite commented on src/components/HomePage.jsx
> +    if (location && jobtype) {
Oh Yes! I'll do that. Am having class at the moment so any time soon!

2021-03-04 05:38 UTC, codingknite commented
> > Hey Faith! So I pretty much made all the changes you suggested except the useRef part as I need your feedback on it.
> > 
> > I also need help with some part of the code.
> > In the HomePage components on line 21,22 & 25, there I declare state for a search URL. That searchUrl is generated once the user fills in the form. But by default, once the application starts for the first time the url should be null for obvious reasons. But setting it to null yields an error.
> > 
> > So I decided to use a fake url: `initUrl (line 21)` which for a fact doesn't return any data once called. Therefore it returns an empty array.
> > 
> > On line 161 I have a condition that only displays SearchedJobs if the array isn't empty i.e an API call was made and we got some data back.
> > This work perfectly except that there are some queries to the API which could potentially return no data i.e an empty array.
> > 
> > My Question: How can I have the url called only when its not null (desired initial state)?
> > Btw I call the API on line 58.
> > 
> > Sorry very long question 🤦
> 
> Cant you just set searchUrl to be an empty string or null.
> Are you having problems using useFetch with an empty string or null?
> 
> Inside useFetch, make a condition that if it the searchURL is null, dont make an api call. 

Such a long question...very easy fix! Thanks for this

2021-03-04 06:12 UTC, idiglove commented on src/components/HomePage.jsx
> +  console.log(searchJobListings);
do you need this console log?

2021-03-04 06:13 UTC, idiglove approved these changes
Looks good now!! Top job ⭐

2021-03-04 07:45 UTC, codingknite commented
> Looks good now!! Top job ⭐

Thank you Faith! Couldn't have a done a thing without your help 🙏

2021-03-04 07:46 UTC, merged